name: dcli_scripts
version: 3.2.0-alpha.2
description: A collection of cli scripts that do odd jobs for me.
repository: https://github.com/open-runtime/dcli_scripts
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  win32: ^5.3.0
  pubspec_manager: ^1.0.0-beta.1
  uuid: ^4.3.3
  docker:
    path: ../docker
  pub_release:
    path: ../pub_release
  dcli:
    path: ../dcli/dcli
  dcli_sdk:
    path: ../dcli/dcli_sdk
  settings_yaml:
   path: ../settings_yaml

dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.25.2

executables:
  add_gnome_launcher:
  artifactory:
  bobthefish:
  certbot_renew:
  clean:
  dcompress:
  dcopydir:
  denv:
  dfind:
  dmailhog:
  dnsflush:
  docker_dcli:
  docker_push:
  downit:
  dmysql:
  dpath:
  dport:
  dreplace:
  dsetver:
  dsort:
  dvirtualbox:
  dwc:
  dwhich:
  dzfs_clean:
  eclipse_launcher:
  find_old_dart_packages:
  find_text:
  gactivate:
  gitadd_team_to_repository:
  gitcreation_date:
  gitgc:
  gituncommited:
  gitsyncfork:
  gitupdate_remote:
  hexdump:
  hog:
  install_flutter:
  ipaddr:
  kill_tomcat:
  pub_get_all:
